### ISSUE TITLE
Support "Light" mode ? 

### ISSUE THREAD

**Issue by src386** [juju2013/MPFA#3]
Actually it works fine with dark background images, because the generated QR code is white, resulting in a good contrast.

Does not work so well with light images however, because white on white result in a QR code that is unreadable.

It would be nice to add a setting to be able to generate a dark QR code.

**Comment by juju2013** [comment]
Well there's no easy way to resolve the equation of white pixel on white background ie. "light mode".

One naif approach is to replace light pixel (RGB value > X) in the background by corresponding B/W pixel value of the original Qrcode, that's what commit 04fc93b7845f03a21ba4c3a4a36b2f3c7570b330 does.

You can see some demo image light-*.png generated by demo.py.

The option to use is "--lmode".
